version: "3.5"
services:
  postgres:
    image: circleci/postgres
    environment:
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: test_db
    volumes:
      - pg_volumn:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - pg_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin_volumn:/root/.pgadmin
    ports:
      - "8079:80"
    networks:
      - pg_network
    restart: unless-stopped

  redis:
    image: bitnami/redis:6.0.9
    restart: always
    environment:
      - REDIS_PASSWORD=redis_1234
    ports:
      - 6379:6379

networks:
  pg_network:
    driver: bridge

volumes:
  pg_volumn:
  pgadmin_volumn:
