name: PR Labeler
on: push

jobs:
  go-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: "1.16.2" # The Go version to download (if necessary) and use.
      # TODO: will make go test instead
      # - run: go run server.go
